### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type __int64問題

### ISSUE THREAD

**Issue by Miocio-nora** [bubbliiiing/yolov7-tiny-pytorch#10]
pytorch                   1.13.0       pytorch-cuda              11.6    python                    3.8.15
報錯如下：
"XXX\yolov7-tiny-pytorch-master\nets\yolo_training.py", line 512, in find_3_positive
    indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type __int64

數據集沒有問題，訓練數據確實也加載進來了，但是開始訓練第一步時報錯，聽説好像是pytorch的版本問題，需要降級為1.11.不知道有什麽別的解決方法。

**Comment by Miocio-nora** [comment]
把yolo_training.py文件512行
indices.append((b, a, gj.clamp_(0, gain[3] - 1), gi.clamp_(0, gain[2] - 1)))
改爲：
indices.append((b, a, gj.clamp_(0, gain[3].long() - 1), gi.clamp_(0, gain[2].long() - 1)))
問題解決。

**Comment by bubbliiiing** [comment]
诶0 0现在还有这个问题吗，我记得之前该国

**Comment by bubbliiiing** [comment]
o……可能改的yolov7那个库
