### ISSUE TITLE
pycocotools和默认的map计算工具测的数据不一致

### ISSUE THREAD

**Issue by realcwj** [bubbliiiing/yolov7-tiny-pytorch#8]
如题，请问怎么能让他保持一致呢？
一是代码里的pycocotools没有输出每个类别的map，只有默认的计算工具才能计算每个类别的map
另外就是mAP等具体数据也不一致，pycocotools更低一点

**Comment by bubbliiiing** [comment]
默认的和coco运算策略不同诶

**Comment by realcwj** [comment]
> 默认的和coco运算策略不同诶

emm那目前项目里的pycocotools只能计算small/medium/large/all，怎么能让它计算各个类别的map呢...
可以简单描述下嘛

**Comment by bubbliiiing** [comment]
估摸着要去coco tools里面处理诶
![image](https://user-images.githubusercontent.com/47347516/204835743-63a35613-60b0-4606-bc00-db430a9a570a.png)
那个k就是种类应该

**Comment by realcwj** [comment]
https://blog.csdn.net/qq_37541097/article/details/112248194根据这篇博文已经解决啦！感谢您抽空答复！

**Comment by jiaduob** [comment]
请问你后来是如何处理pycocotools计算指标和源码计算指标的差异的？我的两种结果差3个点，两个差的有点多，pycocotools的结果差一些
